### ISSUE TITLE
3 - Adaptacion a distintas pantallas

### ISSUE THREAD

**Issue by lucasbarrera** [MasterDjmov/Integrador-DH-Individual#1]
En la seccion de Productos al aumentar el tamaño de la pantalla se genera mucho es pacio libre desde los 361px hasata los 740px 
![issues1](https://github.com/MasterDjmov/Integrador-DH-Individual/assets/89277595/f320f28b-a221-40db-9855-cd7f4c0bef49)
se podria cambiar que en resoluciones intermedias como en tablets tenga dos columnas de tarjetas con width de 45%

**Comment by MasterDjmov** [comment]
Si, había visto y lo deje, pero es buena tu corrección.
![image](https://github.com/MasterDjmov/Integrador-DH-Individual/assets/106092587/99848341-deb1-4712-8498-1c487900abdf)
