### ISSUE TITLE
Bug en diseño responsive (arreglar el mediaquery)

### ISSUE THREAD

**Issue by LCarrizo221** [MasterDjmov/Integrador-DH-Individual#3]
**Problema en el diseño de los contenedores**

- El problema esta en el item en la clase "descuento", se bugea en la resoluciones w564 aprox.

- El problema se encuentra en el main dentro de un div con la clase "product details" el cual por lo que entiendo contiene los items que van dentro de cada tarjeta, el problema viene a que no esta configurada la mediaquery para las resoluciones de tablet, una solucion por ejemplo:

```
/*Tablet*/
/*portrait*/
@media screen and (max-width:768px) and (orientation:landscape) {
    "ajustes del mediaquery"
}
/*fin tablet*/
```

![ERROR1](https://github.com/MasterDjmov/Integrador-DH-Individual/assets/124789829/9d4cd8b5-e9eb-4f5e-9b17-0f5465b5ee99)

- Reconozco que esta me gusto la transición para cuando cambian los items pero si corregís ese error va a quedar de 10 el main 😄

**Comment by MasterDjmov** [comment]
excelente observación, iré ajustando los cambios. gracias
