### ISSUE TITLE
No cumple requisito de las tarjetas (transición del camión verde)

### ISSUE THREAD

**Issue by LCarrizo221** [MasterDjmov/Integrador-DH-Individual#4]
-Un problema minimo, pero que no cumple con el requisito es que: el `hover` del camion se aplique en este mismo item/clase
error:
![image](https://github.com/MasterDjmov/Integrador-DH-Individual/assets/124789829/3d2df377-c7f7-4a02-8be3-b1ddc4309100)

lo que pasa aqui es que el hover se aplica a toda la clase product-article, lo que causa que cuando pones el cursor sobre todo el articulo el camion gira, cuando lo que deberia pasar es que cuando pones el cursor sobre el camion, ahi gira -90deg.

Soluciones:
- Primero utiliza el hover sobre` .product-truck-logo` y aplica ` transform`
- con eso lograras que el hover solo se active cuando el cursor este encima de el icono del camion 😄

**Comment by MasterDjmov** [comment]
claro, en ese caso ellos dieron a optar en clase, o lo aplicabas sobre el camión o sobre el articulo, eso es así, porque si lo vemos por el lado del usuario, al aplicar el mouse sobre el articulo ya realiza la animación, pero sino el usuario ni se entera que el camión gira, solo cuando esta encima, en mi caso opte por el segundo método.
igualmente gracias por tu observación
