### ISSUE TITLE
Sugerencia para los estilos de el register y login

### ISSUE THREAD

**Issue by LCarrizo221** [MasterDjmov/Integrador-DH-Individual#5]
### Me gusta el diseño de la pagina y cumple con los requisitos, pero para que sea mas agradable a la vista de lo que es recomendaria esto:

- Poner todo sobre un div con otro `background.color` de color blanco que contraste con los campos de registro
-  Ajustar los campos requeridos y agregarlerle al hover un border.
![errorRegister](https://github.com/MasterDjmov/Integrador-DH-Individual/assets/124789829/efde4db8-1c52-45c4-8f06-cd8db23b5990)

**Comment by MasterDjmov** [comment]
excelente, ya los cambie
